#define SOUNDNUM_special_effect_C  1
#define SOUNDNUM_special_effect_D  2
#define SOUNDNUM_special_effect_E  3
#define SOUNDNUM_special_effect_F  4
#define SOUNDNUM_electric_piano_C  5
#define SOUNDNUM_electric_piano_D  6
#define SOUNDNUM_electric_piano_E  7
#define SOUNDNUM_electric_piano_F  8
#define SOUNDNUM_organ_C  9
#define SOUNDNUM_organ_D  10
#define SOUNDNUM_organ_E  11
#define SOUNDNUM_organ_F  12
#define SOUNDNUM_ascending_loading_sound  13
#define SOUNDNUM_wierd_wandering_sound  14
#define SOUNDNUM_train_sound_(contact_mic)  15
#define SOUNDNUM_La_Cucaracha  16
#define SOUNDNUM_aaaoooogaaaa  17
#define SOUNDNUM_pew_pew_pew  18
#define SOUNDNUM_boing_harp  19
#define SOUNDNUM_descending_bwaang  20
#define SOUNDNUM_abstract_guitar_reverb  21
#define SOUNDNUM_WoWoWoWoW_machinery_sound  22
#define SOUNDNUM_science_fiction_sound  23
#define SOUNDNUM_introduction  24
